export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const GET_ALL_BRANDS_SUCCESS = "GET_ALL_BRANDS_SUCCESS";
export const GET_ALL_BRANDS_ERROR = "GET_ALL_BRANDS_ERROR";

export const ADD_NEW_BRAND = "ADD_NEW_BRAND";
export const ADD_NEW_BRAND_SUCCESS = "ADD_NEW_BRAND_SUCCESS";
export const ADD_NEW_BRAND_ERROR = "ADD_NEW_BRAND_ERROR";

