export const GET_EGRESSES = "GET_EGRESSES";
export const GET_EGRESSES_ERROR = "GET_EGRESSES_ERROR";
export const GET_EGRESSES_SUCCESS = "GET_EGRESSES_SUCCESS";

export const GET_EGRESS = "GET_EGRESS";
export const GET_EGRESS_ERROR = "GET_EGRESS_ERROR";
export const GET_EGRESS_SUCCESS = "GET_EGRESS_SUCCESS";

export const GET_EGRESSES_CATEGORIES = "GET_EGRESSES_CATEGORIES";
export const GET_EGRESSES_CATEGORIES_ERROR = "GET_EGRESSES_CATEGORIES_ERROR";
export const GET_EGRESSES_CATEGORIES_SUCCESS = "GET_EGRESSES_CATEGORIES_SUCCESS";

export const GET_EGRESSES_SUBCATEGORIES = "GET_EGRESSES_SUBCATEGORIES";
export const GET_EGRESSES_SUBCATEGORIES_ERROR = "GET_EGRESSES_SUBCATEGORIES_ERROR";
export const GET_EGRESSES_SUBCATEGORIES_SUCCESS = "GET_EGRESSES_SUBCATEGORIES_SUCCESS";

export const ADD_EGRESS = "ADD_EGRESS";
export const ADD_EGRESS_ERROR = "ADD_EGRESS_ERROR";
export const ADD_EGRESS_SUCCESS = "ADD_EGRESS_SUCCESS";

