export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEES_ERROR = "GET_EMPLOYEES_ERROR";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";

export const GET_EMPLOYEE = "GET_EMPLOYE";
export const GET_EMPLOYEE_ERROR = "GET_EMPLOYE_ERROR";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYE_SUCCESS";

export const ADD_NEW_EMPLOYE = "ADD_NEW_EMPLOYE";
export const ADD_NEW_EMPLOYE_ERROR = "ADD_NEW_EMPLOYE_ERROR";
export const ADD_NEW_EMPLOYE_SUCCESS = "ADD_NEW_EMPLOYE_SUCCESS";

