export const GET_SALES_REPORTS = "GET_SALES_REPORTS";
export const GET_SALES_REPORTS_SUCCESS = "GET_SALES_REPORTS_SUCCESS";
export const GET_SALES_REPORTS_ERRORS = "GET_SALES_REPORTS_ERRORS";

export const GET_FILTERS = "GET_FILTERS";