export const ADD_NEW_PRODUCT_DETAIL = "ADD_NEW_PRODUCT_DETAIL";
export const VALIDATE_ADD_NEW_PRODUCT_ERROR = "VALIDATE_ADD_NEW_PRODUCT_ERROR";

export const REMOVE_ITEM_PRODUCT_DETAIL = "REMOVE_ITEM_SALE_DETAIL";
export const READ_DATA_NEW_PRODUCT = "READ_DATA_NEW_PRODUCT";

export const GET_ALL_SALES = "GET_ALL_SALES";
export const GET_ALL_SALES_SUCCESS = "GET_ALL_SALESSUCCESS";
export const GET_ALL_SALES_ERROR = "GET_ALL_SALES_ERROR";

export const GET_SALE_BY_ID = "GET_SALE_BY_ID";
export const GET_SALE_BY_ID_SUCCES = "GET_SALE_BY_ID_SUCCES";
export const GET_SALE_BY_ID_ERROR = "GET_SALE_BY_ID_ERROR";

export const POST_NEW_SALE = "POST_NEW_SALE";
export const POST_NEW_SALE_SUCCESS = "POST_NEW_SALE_SUCCESS";
export const POST_NEW_SALE_ERROR = "POST_NEW_SALE_ERROR";

export const FILTER_SALES_LIST = "FILTER_SALES_LIST";

export const CANCEL_SALE = "CANCEL_SALE";
export const CANCEL_SALE_SUCCESS = "CANCEL_SALE_SUCCESS";
export const CANCEL_SALE_ERROR = "CANCEL_SALE_ERROR";


export const EDIT_PRODUCT_SALE_DETAIL = "EDIT_PRODUCT_SALE_DETAIL";
export const EDIT_PRODUCT_SALE_DETAIL_SUCCESS =
    "EDIT_PRODUCT_SALE_DETAIL_SUCCESS";
export const EDIT_PRODUCT_SALE_DETAIL_ERROR = "EDIT_PRODUCT_SALE_DETAIL_ERROR";

export const READ_DATASALE = "READ_DATASALE";
