export const GET_SALES_DETAILS = "GET_SALES_DETAILS";
export const GET_SALES_DETAILS_SUCCESS = "GET_SALES_DETAILS_SUCCESS";
export const GET_SALES_DETAILS_ERROR = "GET_SALES_DETAILS_ERROR";

export const GET_SALE_DETAIL_BY_ID_SALE = "GET_SALE_DETAIL_BY_ID_SALE";
export const GET_SALE_DETAIL_BY_ID_SALE_SUCCESS = "GET_SALE_DETAIL_BY_ID_SALE_SUCCESS";
export const GET_SALE_DETAIL_BY_ID_SALE_ERROR = "GET_SALE_DETAIL_BY_ID_SALE_ERROR";
