export const CONNECT_SOCKET = "CONNECT_SOCKET";
export const CONNECT_SOCKET_SUCCESS = "CONNECT_SOCKET_SUCCESS";
export const CONNECT_SOCKET_ERROR = "CONNECT_SOCKET_ERROR";
export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET";
export const DISCONNECT_SOCKET_SUCCESS = "DISCONNECT_SOCKET_SUCCESS";
export const DISCONNECT_SOCKET_ERROR = "DISCONNECT_SOCKET_ERROR";
